export default {
  BOTTOMTAB: 'BottomTab',
  CUSTOMBUTTON: 'CustomButton',
  CUSTOMINPUT: 'CustomInput',
  SOCIALSIGNINBUTTON: 'SocialSigninBtn',
  MYDRAWER: 'MyDrawer',
  MAINNAVIGATION: 'MainNavigation',
  ADDAGENT: 'AddAgent',
  CHANGEPASSWORD: 'ChangePassword',
  CONFIRMEMAIL: 'ConfirmEmail',
  CONTACTSCREEN: 'ContactScreen',
  CREATEACCOUNT: 'CreateAccount',
  CREATECONTACT: 'CreateContact',
  CRAETEDEAL: 'CreateDeal',
  CREATEORG: 'CreateOrg',
  DEALSCREEN: 'DealScreen',
  FORGOTPASSWORD: 'ForgotPassword',
  LOGINSCREEN: 'LoginScreen',
  MENUE: 'Menue',
  ORGANIZATIONSCREEN: 'OrganizationScreen',
  RESETPASSWORD: 'ResetPassword',
  USERINFO: 'UserInfo',
};
